version: '3'
services:
  jobservice:
    depends_on:
      - rabbitmq
      - jobservicedb
    env_file:
      - ./rabbitmq.env
    environment:
      CAF_DATABASE_URL: jdbc:postgresql://jobservicedb:5432/jobservice
      CAF_DATABASE_USERNAME: postgres
      CAF_DATABASE_PASSWORD: root
      CAF_STATUS_CHECK_TIME: 5
      CAF_TRACKING_PIPE: jobtracking-in
      CAF_WEBSERVICE_URL: http://jobservice:8080/job-service/v1
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/job-service:1.10.0-SNAPSHOT
    ports:
      - "${JOB_SERVICE_PORT:-9411}:8080"

  jobservicedb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/job-service-postgres:1.10.0-SNAPSHOT
    volumes:
      - job-service-db:/var/lib/postgresql/data

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  worker-batch:
    depends_on:
      - rabbitmq
    env_file:
      - ./rabbitmq.env
    environment:
      CAF_WORKER_INPUT_QUEUE: batch-in
      CAF_BATCH_WORKER_ERROR_QUEUE: batch-err
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/worker-batch-fs:1.12.0-SNAPSHOT
    volumes:
      - ./batch-plugins:/mnt/mesos/sandbox/batch-plugins:ro
      - ${JOB_SERVICE_DEMO_DIR:-./demo-dir}:/mnt/caf-datastore-root

  worker-jobtracking:
    depends_on:
      - rabbitmq
      - jobservicedb
    env_file:
      - ./rabbitmq.env
    environment:
      CAF_WORKER_INPUT_QUEUE: jobtracking-in
      CAF_WORKER_OUTPUT_QUEUE: jobtracking-out
      CAF_WORKER_REJECTED_QUEUE: jobtracking-rejected
      JOB_DATABASE_URL: jdbc:postgresql://jobservicedb:5432/jobservice
      JOB_DATABASE_USERNAME: postgres
      JOB_DATABASE_PASSWORD: root
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/worker-jobtracking:1.10.0-SNAPSHOT

  worker-langdetect:
    depends_on:
      - rabbitmq
    env_file:
      - ./rabbitmq.env
    environment:
      CAF_WORKER_INPUT_QUEUE: languageidentification-in
      CAF_WORKER_OUTPUT_QUEUE: languageidentification-out
      CAF_WORKER_REJECTED_QUEUE: languageidentification-rejected
      CAF_LANG_DETECT_WORKER_OUTPUT_FOLDER: /mnt/caf-datastore-root/output-items
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/worker-languagedetection:1.0.0-SNAPSHOT
    volumes:
      - ${JOB_SERVICE_DEMO_DIR:-./demo-dir}:/mnt/caf-datastore-root

volumes:
  job-service-db:
  rabbitmq:
  worker-datastore:
