apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobservicedb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: ${maven.build.timestamp}
      labels:
        io.kompose.service: jobservicedb
    spec:
      containers:
      - name: jobservicedb
        image: postgres:9.6
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          value: "${JOB_SERVICE_DB_PASSWORD}"
        - name: POSTGRES_USER
          value: "${JOB_SERVICE_DB_USER}"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: job-service-db
        ports:
        - containerPort: 5432
          hostPort: ${JOB_SERVICE_DB_PORT}
      volumes:
      - name: job-service-db
        persistentVolumeClaim:
          claimName: job-service-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: ${maven.build.timestamp}
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        imagePullPolicy: Always
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
        ports:
        - containerPort: 5672
          hostPort: ${CAF_RABBITMQ_PORT}
        - containerPort: 15672
          hostPort: ${CAF_RABBITMQ_MANAGEMENT_PORT}
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
