version: '3'
services:
  jobservice:
    env_file:
      - ./rabbitmq.env
    environment:
      JOB_DATABASE_URL: "jdbc:postgresql://${JOB_SERVICE_DB_HOST}:${JOB_SERVICE_DB_PORT}/jobservice"
      JOB_DATABASE_APPNAME: "Job Service"
      JOB_DATABASE_USERNAME: "${JOB_DATABASE_USERNAME}"
      JOB_DATABASE_PASSWORD: "${JOB_DATABASE_PASSWORD}"
      CAF_STATUS_CHECK_TIME: 5
      CAF_TRACKING_PIPE: jobtracking-in
      CAF_WEBSERVICE_URL: "http://${JOB_SERVICE_DOCKER_HOST}:${JOB_SERVICE_PORT}/job-service/v1"
    image: jobservice/job-service:${project.version}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "${JOB_SERVICE_PORT}:8080"

  worker-jobtracking:
    env_file:
      - ./rabbitmq.env
    environment:
      JOB_DATABASE_APPNAME: "Job Tracking Worker"
      CAF_WORKER_INPUT_QUEUE: jobtracking-in
      CAF_WORKER_ERROR_QUEUE: jobtracking-err
      JOB_DATABASE_URL: "jdbc:postgresql://${JOB_SERVICE_DB_HOST}:${JOB_SERVICE_DB_PORT}/jobservice"
      JOB_DATABASE_USERNAME: "${JOB_DATABASE_USERNAME}"
      JOB_DATABASE_PASSWORD: "${JOB_DATABASE_PASSWORD}"
      CAF_WEBSERVICE_URL: "http://${JOB_SERVICE_DOCKER_HOST}:${JOB_SERVICE_PORT}/job-service/v1"
    image: jobservice/worker-jobtracking:${project.version}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      update_config:
        parallelism: 1
        delay: 10s

  jobservicescheduledexecutor:
    env_file:
      - ./rabbitmq.env
    environment:
      JOB_DATABASE_APPNAME: "Job Service Scheduled Executor"
      CAF_WORKER_INPUT_QUEUE: jobservicescheduler-in
      JOB_DATABASE_URL: "jdbc:postgresql://${JOB_SERVICE_DB_HOST}:${JOB_SERVICE_DB_PORT}/jobservice"
      JOB_DATABASE_USERNAME: "${JOB_DATABASE_USERNAME}"
      JOB_DATABASE_PASSWORD: "${JOB_DATABASE_PASSWORD}"
      CAF_STATUS_CHECK_TIME: 5
      CAF_TRACKING_PIPE: jobtracking-in
      CAF_WEBSERVICE_URL: "http://${JOB_SERVICE_DOCKER_HOST}:${JOB_SERVICE_PORT}/job-service/v1"
      CAF_SCHEDULED_EXECUTOR_PERIOD: 10	  
    image: jobservice/job-service-scheduled-executor:${project.version}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
