apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-globfilter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: ${maven.build.timestamp}
      labels:
        io.kompose.service: worker-globfilter
    spec:
      containers:
      - name: worker-globfilter
        image: ${worker-globfilter.version}
        imagePullPolicy: Always
        env:
        - name: CAF_BATCH_WORKER_ERROR_QUEUE
          value: "${CAF_BATCH_WORKER_ERROR_QUEUE}"
        - name: CAF_GLOB_WORKER_BINARY_DATA_INPUT_FOLDER
          value: "${CAF_GLOB_WORKER_BINARY_DATA_INPUT_FOLDER}"
        - name: CAF_RABBITMQ_HOST
          value: "${CAF_RABBITMQ_HOST}"
        - name: CAF_RABBITMQ_PORT
          value: "${CAF_RABBITMQ_PORT}"
        - name: CAF_RABBITMQ_PASSWORD
          value: "${CAF_RABBITMQ_PASSWORD}"
        - name: CAF_RABBITMQ_USERNAME
          value: "${CAF_RABBITMQ_USERNAME}"
        - name: CAF_WORKER_INPUT_QUEUE
          value: "${CAF_WORKER_GLOBFILTER_INPUT_QUEUE}"
        volumeMounts:
          - mountPath: /mnt/caf-datastore-root
            name: worker-datastore
          - mountPath: /mnt/caf-worker-input-dir
            name: job-service-demo-input-dir
      volumes:
      - name: worker-datastore
        persistentVolumeClaim:
          claimName: worker-datastore
      - name: job-service-demo-input-dir
        hostPath:
          path: ${JOB_SERVICE_DEMO_INPUT_DIR}
          type: DirectoryOrCreate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-langdetect
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: ${maven.build.timestamp}
      labels:
        io.kompose.service: worker-langdetect
    spec:
      containers:
      - name: worker-langdetect
        image: ${worker-langdetect.version}
        imagePullPolicy: Always
        env:
        - name: CAF_RABBITMQ_HOST
          value: "${CAF_RABBITMQ_HOST}"
        - name: CAF_RABBITMQ_PORT
          value: "${CAF_RABBITMQ_PORT}"
        - name: CAF_RABBITMQ_PASSWORD
          value: "${CAF_RABBITMQ_PASSWORD}"
        - name: CAF_RABBITMQ_USERNAME
          value: "${CAF_RABBITMQ_USERNAME}"
        - name: CAF_WORKER_INPUT_QUEUE
          value: "${CAF_WORKER_LANGDETECT_INPUT_QUEUE}"
        - name: CAF_WORKER_OUTPUT_QUEUE
          value: "${CAF_WORKER_LANGDETECT_OUTPUT_QUEUE}"
        - name: CAF_LANG_DETECT_WORKER_OUTPUT_FOLDER
          value: "${CAF_LANG_DETECT_WORKER_OUTPUT_FOLDER}"
        volumeMounts:
          - mountPath: /mnt/caf-datastore-root
            name: worker-datastore
          - mountPath: /mnt/caf-worker-output-dir
            name: job-service-demo-output-dir
      volumes:
      - name: worker-datastore
        persistentVolumeClaim:
          claimName: worker-datastore
      - name: job-service-demo-output-dir
        hostPath:
          path: ${JOB_SERVICE_DEMO_OUTPUT_DIR}
          type: DirectoryOrCreate
