apiVersion: v1
kind: ConfigMap
metadata:
  name: jobservice-config
data:
  JOB_SERVICE_DB_PASSWORD: postgres
  JOB_DATABASE_URL: jdbc:postgresql://jobservicedb:5432/jobservice
  JOB_SERVICE_DB_USER: postgres
  JOB_DATABASE_APPNAME_JOBSERVICE: Job Service
  JOB_DATABASE_APPNAME_JOBTRACKING: Job Tracking Worker
  JOB_DATABASE_APPNAME_SCHEDULED_EXECUTOR: Job Service Scheduled Executor
  CAF_RABBITMQ_HOST: rabbitmq
  CAF_RABBITMQ_PORT: "5672"
  CAF_RABBITMQ_USERNAME: guest
  CAF_RABBITMQ_PASSWORD: guest
  CAF_WEBSERVICE_URL: http://jobservice:8080/job-service/v1
  
