swagger: "2.0"
info:
  title: "Job Service"
  version: "1.0"
  description: |
    Allows background operations to be sent to the workers, and for the
    operations to be tracked and controlled.

    You can check the progress of operations, and request to cancel, pause, or resume them.  *NB: Pause and Resume are future
    requirements.*

    The primary use of this functionality is batch document
    processing.  The service can send work to the Batch Worker, and
    then track the progress of that work.
basePath: /job-service/v1
tags:
  - name: Jobs
    description: Job Control
consumes:
  - application/json
produces:
  - application/json
paths:
  /jobs:
    parameters:
      - name: CAF-Correlation-Id
        in: header
        type: string
        description: |
          An identifier that correlates events 
          across different services.
    get:
      tags:
        - Jobs
      summary: Gets the list of jobs
      description: Returns the list of job definitions defined in the system.
      operationId: getJobs
      responses:
        200:
          description: Returns the list of jobs.
          schema:
            type: array
            items:
              $ref: "#/definitions/job"
  /jobs/{jobId}:
    parameters:
      - name: CAF-Correlation-Id
        in: header
        type: string
        description: |
          An identifier that correlates events 
          across different services.
      - name: jobId
        in: path
        type: string
        required: true
        description: The identifier of the job
    get:
      tags:
        - Jobs
      summary: Gets the specified job.
      description: Retrieves information about the specified job.
      operationId: getJob
      responses:
        200:
          description: Returns the job data.
          schema:
            $ref: "#/definitions/job"
        400:
          description: The `jobId` parameter contains invalid characters.
        404:
          description: The specified job is not found.
    put:
      tags:
        - Jobs
      summary: Adds a new job.
      description: |
        Creates the specified job using the job definition included in the http
        body.
      operationId: createOrUpdateJob
      parameters:
        - name: newJob
          description: The definition of the job to create
          in: body
          required: true
          schema:
            $ref: "#/definitions/newJob"
      responses:
        201:
          description: Indicates that the job was successfully created.
        204:
          description: Indicates that the job was successfully updated.
        400:
          description: The `jobId` parameter contains invalid characters.
    delete:
      tags:
        - Jobs
      summary: Deletes the specified job.
      description: Deletes the specified job from the system.
      operationId: deleteJob
      responses:
        204:
          description: Indicates that the job was successfully deleted.
        400:
          description: The `jobId` parameter contains invalid characters.
        404:
          description: The specified job is not found.
  /jobs/{jobId}/isActive:
    parameters:
      - name: CAF-Correlation-Id
        in: header
        type: string
        description: |
          An identifier that correlates events 
          across different services.
      - name: jobId
        in: path
        type: string
        required: true
        description: The identifier of the job
    get:
      tags:
        - Jobs
      summary: Checks whether the job is active.
      description: Checks whether the specified job is active.
      operationId: getJobActive
      responses:
        200:
          description: Returns whether the job is active.
          schema:
            type: boolean
          headers:
            CacheableJobStatus:
                description: A response that includes this header with the value ‘true’ is eligible for caching in a cache specific to job status responses.
                type: boolean
        400:
          description: The `jobId` parameter contains invalid characters.
  /jobs/{jobId}/cancel:
    parameters:
      - name: CAF-Correlation-Id
        in: header
        type: string
        description: |
          An identifier that correlates events 
          across different CAF services
      - name: jobId
        in: path
        type: string
        required: true
        description: The identifier of the job
    post:
      tags:
        - Jobs
      summary: Cancels the job.
      description: Cancels the specified job.
      operationId: cancelJob
      responses:
        204:
          description: The cancellation has been accepted.
        400:
          description: The `jobId` parameter contains invalid characters.
        404:
          description: The specified job is not found.
definitions:
  newJob:
    type: object
    properties:
      name:
        type: string
        description: The name of the job
      description:
        type: string
        description: The description of the job
      externalData:
        # TODO: Should we make this more structured than just string
        #       Name/Value Pairs perhaps
        #       Or possibly even more structured than that - storing in xml
        #       would mean xpath searches could be done later
        type: string
        description: |
          External data can be associated with the job for use by other
          components.
      task:
        $ref: "#/definitions/worker-action"
  worker-action:
    type: object
    required:
      - taskClassifier
      - taskApiVersion
      - taskData
      - taskPipe
      - targetPipe
    properties:
      taskClassifier:
        type: string
      taskApiVersion:
        type: integer
        format: int32
      taskData:
        type: string
      taskDataEncoding:
        type: string
        default: utf8
        enum:
          - utf8
          - base64
      taskPipe:
        type: string
      targetPipe:
        type: string
  job:
    type: object
    properties:
      id:
        type: string
        description: The job identifier
      name:
        type: string
        description: The name of the job
      description:
        type: string
        description: The description of the job
      externalData:
        type: string
        description: |
          External data can be associated with the job for use by other
          components.
      createTime:
        type: string
        format: date-time
        description: The time the job was created
      status:
        type: string
        description: The status of the job
        enum:
          - Active
          - Cancelled
          - Completed
          - Failed
          - Paused
          - Waiting
      percentageComplete:
        type: number
        format: float
        description: Gives an indication of the progress of the job.
      failures:
        type: array
        items:
          $ref: "#/definitions/failure"
        description: Job failure details
  failure:
    type: object
    properties:
      failureId:
        type: string
      failureTime:
        type: string
        format: date-time
      failureSource:
        type: string
      failureMessage:
        type: string
